FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\SpellSystem.bf", "src\\components\\RigidBody.bf", "src\\PhysicsSystem.bf", "src\\ParticleSystem.bf", "src\\components\\Particle.bf", "src\\generated\\Entity.bf", "src\\Entity.bf", "src\\components\\Spell.bf", "src\\Exports.bf", "src\\components\\PlayerTag.bf", "src\\CompSerializationRegistry.bf", "src\\components\\Controller.bf", "src\\components\\Pickup.bf", "src\\generated\\EKeyCode.bf", "src\\System.bf", "src\\TestSystem.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Reflection\\TypeInstance.bf"]

[MainWindow]
X = 772
Y = 0
Width = 500
Height = 470
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 348.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ParticleSystem.bf"
TabWidth = 128.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ParticleSystem.bf"
CursorPos = 303
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Particle.bf"
TabWidth = 87.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Particle.bf"
CursorPos = 257
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\generated\\Entity.bf"
CursorPos = 1775
VertPos = 690.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Entity.bf"
CursorPos = 2029
VertPos = 1104.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SpellSystem.bf"
TabWidth = 114.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\SpellSystem.bf"
CursorPos = 2034
VertPos = 690.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "PhysicsSystem.bf"
TabWidth = 127.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\PhysicsSystem.bf"
CursorPos = 1191
VertPos = 673.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Pickup.bf"
TabWidth = 82.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Pickup.bf"
CursorPos = 54
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Spell.bf"
TabWidth = 73.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Spell.bf"
CursorPos = 180
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EKeyCode.bf"
TabWidth = 104.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\generated\\EKeyCode.bf"
CursorPos = 82
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Controller.bf"
TabWidth = 102.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Controller.bf"
CursorPos = 215
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CompSerializationRegistry.bf"
TabWidth = 197.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\CompSerializationRegistry.bf"
CursorPos = 4110
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "PlayerTag.bf"
TabWidth = 101.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\PlayerTag.bf"
CursorPos = 96
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Exports.bf"
TabWidth = 89.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Exports.bf"
CursorPos = 7016
VertPos = 2967.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "System.bf"
TabWidth = 86.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\System.bf"
CursorPos = 123
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TestSystem.bf"
TabWidth = 109.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\TestSystem.bf"
CursorPos = 325
VertPos = 966.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 166.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
