FileVersion = 1
Dependencies = {corlib = "*", corlib = "*", corlib = "*", corlib = "*"}

[Project]
Name = "beef-hush"
TargetType = "BeefLib"
StartupObject = "beef_hush.Program"

[[Project.DistinctOptions]]
Filter = ""
EmitDebugInfo = "Yes"
RuntimeChecks = false

[Configs.Debug.Win64]
BuildKind = "DynamicLib"
BeefLibType = "DynamicDebug"
