FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["src\\SpellSystem.bf", "src\\TestSystem.bf", "src\\components\\Spell.bf", "src\\components\\MovementStat.bf", "src\\MovementSystem.bf", "src\\generated\\InputManager.bf", "src\\ParticleSystem.bf", "src\\EnvironmentSystem.bf", "src\\PhysicsSystem.bf", "src\\components\\AABB.bf", "src\\generated\\Entity.bf", "src\\LifetimeSystem.bf", "src\\hacked\\WorldTransform.bf", "src\\components\\Particle.bf", "src\\Entity.bf", "src\\components\\PlayerTag.bf", "src\\components\\Pickup.bf"]

[MainWindow]
X = 772
Y = 0
Width = 500
Height = 470
ShowKind = "ShowMaximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 348.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
TabIsPinned = false
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MovementStat.bf"
TabWidth = 129.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\MovementStat.bf"
CursorPos = 116
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "InputManager.bf"
TabWidth = 126.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\generated\\InputManager.bf"
CursorPos = 301
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MovementSystem.bf"
TabWidth = 148.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\MovementSystem.bf"
CursorPos = 1657
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "WorldTransform.bf"
TabWidth = 140.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\hacked\\WorldTransform.bf"
CursorPos = 256
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "EnvironmentSystem.bf"
TabWidth = 158.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\EnvironmentSystem.bf"
CursorPos = 220
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ParticleSystem.bf"
TabWidth = 128.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\ParticleSystem.bf"
CursorPos = 230
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Particle.bf"
TabWidth = 87.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Particle.bf"
CursorPos = 257
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\generated\\Entity.bf"
CursorPos = 1775
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Entity.bf"
TabWidth = 76.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\Entity.bf"
CursorPos = 1811
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "SpellSystem.bf"
TabWidth = 114.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\SpellSystem.bf"
CursorPos = 2493
VertPos = 1417.0
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "PhysicsSystem.bf"
TabWidth = 127.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\PhysicsSystem.bf"
CursorPos = 982
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Pickup.bf"
TabWidth = 82.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Pickup.bf"
CursorPos = 54
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Spell.bf"
TabWidth = 73.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\Spell.bf"
CursorPos = 180
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "PlayerTag.bf"
TabWidth = 101.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\components\\PlayerTag.bf"
CursorPos = 96
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "System.bf"
TabWidth = 86.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\System.bf"
CursorPos = 123
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "TestSystem.bf"
TabWidth = 109.0
TabIsPinned = false
Type = "SourceViewPanel"
FilePath = "src\\TestSystem.bf"
CursorPos = 325
ProjectName = "beef-hush"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 289.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
TabIsPinned = false
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
TabIsPinned = false
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
TabIsPinned = false
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 1272.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
TabIsPinned = false
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
TabIsPinned = false
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
TabIsPinned = false
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
TabIsPinned = false
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
TabIsPinned = false
Type = "OutputPanel"

[[BookmarkFolders]]
Title = ""

[OutputFilters]
ModuleLoadMessages = false
ModuleUnloadMessages = false
ProcessExitMessages = false
ThreadCreateMessages = false
ThreadExitMessages = false
SymbolLoadMessages = false
ProgramOutput = false
